version: '2.1'

services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres@desafiostonebd
      PGPASSWORD: DesafioStone1
      PGDATABASE: bankchallenge
      PGDATABASE_ES: bankchallenge_es
      PGPORT: 5432
      PGHOST: desafiostonebd.postgres.database.azure.com
    ports:
      - 80:4000